version: '3.8'

services:
  esp-cam-server:
    image: ghcr.io/hartmannlight/esp-cam-server:latest
    restart: unless-stopped
    volumes:
      - ./config.yml:/app/config.yml:ro
      - ./data:/app/data
